apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gobg
  name: gobg-route
spec:
  host: ""
  port:
    targetPort: 8080
  to:
    kind: Service
    name: gobg
    weight: 100
