name: vCluster Instance Deploy

on:
  pull_request:
    types: 
      - labeled

jobs:
  create-vcluster-instance:
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          echo ${{ github.event.pull_request.number }}
          echo ${{ secrets.AKUITY_KEY_ID }}
          echo ${{ secrets.AKUITY_KEY_SECRET }}
          echo ${{ secrets.AKUITY_INSTANCE_NAME }}
          echo ${{ secrets.AKUITY_ORG_NAME }}
          echo ${{ secrets.PUBLIC_K8S_CONFIG }}
          echo '================================'
          echo ${{ secrets.PUBLIC_K8S_CONFIG }} | base64 -d
