name: vCluster Instance Deploy

on:
  pull_request:
    types: 
      - labeled

jobs:
  create-vcluster-instance:
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          cat <<-EOF
          apiVersion: management.loft.sh/v1
          kind: VirtualClusterInstance
          metadata:
            name: gobg-preview-${{ github.event.pull_request.number }}
            namespace: loft-p-vcluster-demo # Project is called vcluster-demo
          spec:
            displayName: gobg-preview-${{ github.event.pull_request.number }}
            owner:
              user: admin
            templateRef:
              name: vcluster-akuity-template
            parameters: |
              prnumber: "${{ github.event.pull_request.number }}"
              akuityKeyId: "${{ secrets.AKUITY_KEY_ID }}"
              akuityKeySecret: "${{ secrets.AKUITY_KEY_SECRET }}"
              akuityOrgName: "${{ secrets.AKUITY_ORG_NAME }}"
              akuityInstanceName: "${{ secrets.AKUITY_INSTANCE_NAME }}"
          EOF
          echo '================================'
          echo ${{ secrets.PUBLIC_K8S_CONFIG }}
          echo '================================'
          echo ${{ secrets.PUBLIC_K8S_CONFIG }} | base64 -d
