name: vCluster Instance Deploy

on: [push]

jobs:
  create-vcluster-instance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          pwd
          which kubectl
          tree .
