name: vCluster Instance Delete

on:
  pull_request:
    types: 
      - closed
    branches: 
      - main

jobs:
  delete-vcluster-instance:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Create vCluster for the Pull Request
        run: |
          ## Download the Akuity CLI
          arch=$(uname -m)
          ver=v0.20.1
          [[ ${arch} == "x86_64" ]] && arch=amd64
          [[ ${arch} == "aarch64" ]] && arch=arm64
          wget -O /usr/local/bin/akuity -q "https://dl.akuity.io/akuity-cli/${ver}/linux/${arch}/akuity"
          chmod +x /usr/local/bin/akuity

          ## Download vCluster CLI
          curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/download/v0.22.4/vcluster-linux-amd64"
          mv vcluster /usr/local/bin
          chmod +x /usr/local/bin/vcluster

          ## Export Akuity Keys for the CLI
          export AKUITY_API_KEY_ID=${{ secrets.AKUITY_KEY_ID }}
          export AKUITY_API_KEY_SECRET=${{ secrets.AKUITY_KEY_SECRET }}

          ## Delete Akuity cluster definition
          akuity argocd cluster delete --organization-name=${{ secrets.AKUITY_ORG_NAME }} --instance-name=${{ secrets.AKUITY_INSTANCE_NAME }} gobg-preview-${{ github.event.pull_request.number }} 

          ## Login to instance
          vcluster platform login --insecure ${{ secrets.VCLUSTER_PRO_HOSTNAME }} --access-key ${{ secrets.LOFT_ACCESS_KEY }}

          ## Delete vCluster Instance
          vcluster platform delete gobg-preview-${{ github.event.pull_request.number }} --project ${{ secrets.VCLUSTER_PRO_PROJECT }} --wait=false
