name: vCluster Instance Deploy

on:
  pull_request:
    types: 
      - labeled

jobs:
  create-vcluster-instance:
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create vCluster for the Pull Request
        run: |
          ## Download vCluster CLI
          curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/download/v0.22.4/vcluster-linux-amd64" 
          mv vcluster /usr/local/bin 
          chmod +x /usr/local/bin/vcluster

          ## Login to instance
          vcluster login --insecure ${{ secrets.VCLUSTER_PRO_HOSTNAME }} --access-key ${{ secrets.LOFT_ACCESS_KEY }}

          ## Create Instance
          vcluster create gobg-preview-${{ github.event.pull_request.number }} --distro k3s --skip-wait \
          --project ${{ secrets.VCLUSTER_PRO_PROJECT }} --recreate --driver platform --template ${{ secrets.VCLUSTER_PRO_TEMPLATE }} \
          --set-param prnumber="${{ github.event.pull_request.number }}" \
          --set-param akuityKeyId="${{ secrets.AKUITY_KEY_ID }}" \
          --set-param akuityKeySecret="${{ secrets.AKUITY_KEY_SECRET }}" \
          --set-param akuityOrgName="${{ secrets.AKUITY_ORG_NAME }}" \
          --set-param akuityInstanceName="${{ secrets.AKUITY_INSTANCE_NAME }}"
